-- 删除旧表（如果存在）
DROP TABLE IF EXISTS merchant_rankings;

-- 创建新表
CREATE TABLE merchant_rankings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  rating DECIMAL(3,1) DEFAULT 0.0,
  price VARCHAR(50),
  area VARCHAR(100),
  tag VARCHAR(255),
  address TEXT,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  phone VARCHAR(50),
  business_hours TEXT,
  description TEXT,
  image_url TEXT,
  amap_id VARCHAR(100),
  favorite_count INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  ranking_score DECIMAL(4,2) DEFAULT 0.00,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_merchant_category ON merchant_rankings(category);
CREATE INDEX IF NOT EXISTS idx_merchant_rating ON merchant_rankings(rating);
CREATE INDEX IF NOT EXISTS idx_merchant_area ON merchant_rankings(area);
CREATE INDEX IF NOT EXISTS idx_merchant_featured ON merchant_rankings(is_featured);
